### PR TITLE
Update vendor countdown.js to v2.5.2

### PR DESCRIPTION
**Pull request by ylastapis**
Hi, 

I need the v2.5.2 of CountdownJs to have access to setLabels method.
Does not seem to work with the V2.3.4.

I just get the last versions from http://countdownjs.org/

Thx.

### CODE REVIEW

**Comment by icambron** [comment]
Thanks!

**Comment by pixelchutes** [comment]
I'm attempting to use this against `HEAD` but keep running into: `Uncaught TypeError: setLabels is not a function`.

I have confirmed countdown.js is serving up v2.5.2, as well.

**Is this the correct syntax:**

```JavaScript
moment("2015-02-19T12:00:00-0400").countdown("2015-02-19T12:00:00-0400").setLabels(
		null,
		null,
		null,
		null,
		'Now.'
	).toString();
```

**Comment by ylastapis** [comment]
Hi !

just do : 
~~~javascript
countdown.setLabels(
    null,
    null,
    null,
    null,
    'Now.'
);

moment("2015-02-19T12:00:00-0400").countdown("2015-02-19T12:00:00-0400").toString();
~~~

That will output in your example : 

~~~
Now.
~~~
